### ISSUE TITLE
gcc-11: `orbit/src/LinuxTracing/PerfEventReaders.cpp:108:38`: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]

### ISSUE THREAD

**Issue by jiridanek** [google/orbit#3453]
This happens on my machine with gcc-11

```
[ 43%] Building CXX object src/UserSpaceInstrumentation/CMakeFiles/UserSpaceInstrumentation.dir/FindFunctionAddress.cpp.o
/home/jdanek/repos/orbit/src/LinuxTracing/PerfEventReaders.cpp: In function 'orbit_linux_tracing::MmapPerfEvent orbit_linux_tracing::ConsumeMmapPerfEvent(orbit_linux_tracing::PerfEventRingBuffer*, const perf_event_header&)':
/home/jdanek/repos/orbit/src/LinuxTracing/PerfEventReaders.cpp:108:38: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  108 |   filename_vector[filename_size - 1] = '\0';
cc1plus: some warnings being treated as errors
gmake[2]: *** [src/LinuxTracing/CMakeFiles/LinuxTracing.dir/build.make:206: src/LinuxTracing/CMakeFiles/LinuxTracing.dir/PerfEventReaders.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```

```
commit 02f72c7311ed08e6418ecbfab4a457db67aa38d9 (HEAD -> main, origin/main, origin/HEAD)
Author: ronaldfw <wotzlaw@google.com>
Date:   Fri Mar 18 17:55:05 2022 +0100

    Fix bug handling UWOP_SET_FPREG unwind code
```

```
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jiridanek** [comment]
Next, after workarounding the previous warning, I got

```
/home/jdanek/repos/orbit/src/OrbitGl/BatcherTest.cpp: In lambda function:
/home/jdanek/repos/orbit/src/OrbitGl/BatcherTest.cpp:253:20: error: '<anonymous>' may be used uninitialized [-Werror=maybe-uninitialized]
  253 |     batcher.AddLine(Vec2(0.f, 0.f), Vec2(1.f, 1.f), 0.f, Color());
      |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jdanek/repos/orbit/src/OrbitGl/BatcherTest.cpp:13:
/home/jdanek/repos/orbit/src/OrbitGl/Batcher.h:124:8: note: by argument 5 of type 'const Color&' {aka 'const gte::Vector4<unsigned char>&'} to 'void Batcher::AddLine(Vec2, Vec2, float, const Color&, std::unique_ptr<PickingUserData>)' declared here
  124 |   void AddLine(Vec2 from, Vec2 to, float z, const Color& color,
      |        ^~~~~~~
/home/jdanek/repos/orbit/src/OrbitGl/BatcherTest.cpp:253:64: note: '<anonymous>' declared here
  253 |     batcher.AddLine(Vec2(0.f, 0.f), Vec2(1.f, 1.f), 0.f, Color());
      |  
```

**Comment by florian-kuebler** [comment]
Unfortunately, we don't support compiling with gcc-11, yet. Switching to gcc-10 or clang-11 would be the easiest solution.
To do so, e.g. run `.build.sh clang11_relwithdebinfo` or `./bootstrap.sh clang11_relwithdebinfo`.

However, I will also look into the reported issues with gcc-11.

**Comment by jiridanek** [comment]
Thanks. The easiest for me was to edit the code to get it compiling with gcc-11 (mostly commenting out tests). I considered getting a supported compiler from either Nixpkgs or LinuxBrew, or compiling it from source, but in the end I got it working with gcc-11 (11.2).

Thanks for being willing to look into it!

```diff
diff --git a/src/LinuxTracing/PerfEventReaders.cpp b/src/LinuxTracing/PerfEventReaders.cpp
index c5c1ada1..52460107 100644
--- a/src/LinuxTracing/PerfEventReaders.cpp
+++ b/src/LinuxTracing/PerfEventReaders.cpp
@@ -105,7 +105,7 @@ MmapPerfEvent ConsumeMmapPerfEvent(PerfEventRingBuffer* ring_buffer,
   std::vector<char> filename_vector(filename_size);
   ring_buffer->ReadRawAtOffset(&filename_vector[0], filename_offset, filename_size);
   // This is a bit paranoid but you never know
-  filename_vector[filename_size - 1] = '\0';
+  if(filename_size > 0) filename_vector[filename_size - 1] = '\0';
   std::string filename(filename_vector.data());
 
   ring_buffer->SkipRecord(header);
diff --git a/src/OrbitGl/BatcherTest.cpp b/src/OrbitGl/BatcherTest.cpp
index 4594fee0..ffff403b 100644
--- a/src/OrbitGl/BatcherTest.cpp
+++ b/src/OrbitGl/BatcherTest.cpp
@@ -249,10 +249,10 @@ TEST(Batcher, TranslationsAreAutomaticallyAdded) {
                                      original_expectation.end_point + transform};
   auto it = buffers.line_buffer.lines_.begin();
 
-  const auto add_line_assert_eq = [&batcher, &it](const Line& expectation) {
-    batcher.AddLine(Vec2(0.f, 0.f), Vec2(1.f, 1.f), 0.f, Color());
+  const auto add_line_assert_eq = [&batcher, &it](const Line&) {
+//     batcher.AddLine(Vec2(0.f, 0.f), Vec2(1.f, 1.f), 0.f, Color());
     ++it;
-    ASSERT_TRUE(LineEq(expectation, *it));
+//     ASSERT_TRUE(LineEq(expectation, *it));
   };
 
   ASSERT_TRUE(LineEq(original_expectation, *it));
@@ -271,4 +271,4 @@ TEST(Batcher, TranslationsAreAutomaticallyAdded) {
   ASSERT_DEATH(batcher.PopTranslation(), "Check failed");
 }
 
-}  // namespace
\ No newline at end of file
+}  // namespace
diff --git a/third_party/conan/configs/linux/settings.yml b/third_party/conan/configs/linux/settings.yml
index 1901e12a..6e797b4f 100644
--- a/third_party/conan/configs/linux/settings.yml
+++ b/third_party/conan/configs/linux/settings.yml
@@ -52,7 +52,7 @@ compiler:
                   "7", "7.1", "7.2", "7.3", "7.4", "7.5",
                   "8", "8.1", "8.2", "8.3", "8.4",
                   "9", "9.1", "9.2", "9.3",
-                  "10", "10.1"]
+                  "10", "10.1", "11.2"]
         libcxx: [libstdc++, libstdc++11]
         threads: [None, posix, win32] #  Windows MinGW
```

**Comment by damienrg** [comment]
Close this issue as https://github.com/google/orbit/pull/3708 has been merged?

**Comment by beckerhe** [comment]
Yep. Closing this. Thx.
